# Generated by Django 3.2.9 on 2022-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rera_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='upload_doc',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
