# Generated by Django 3.2.9 on 2022-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rera_approved',
            field=models.CharField(default=False, max_length=4),
        ),
    ]
