# Generated by Django 3.2.9 on 2022-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_rera_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rera_approved',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
