# Generated by Django 3.2.9 on 2022-01-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='phone',
        ),
    ]
