# Generated by Django 3.2.9 on 2022-01-08 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='phoneNumber',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d[\\d -]{8,12}\\d$')]),
        ),
    ]
