# Generated by Django 3.2.9 on 2022-01-08 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20220108_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d[\\d -]{8,12}\\d$')]),
        ),
    ]
